version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  test-unit:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A familiar hi"
  test-integration:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A cool wave"
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A final goodbye"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-unit:
          # run only if/when build succeeds
          requires:
            - build
      - test-integration:
          # run only if/when build succeeds
          requires:
            - build
      - deploy:
          requires:
            - test-unit
            - test-integration
