version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "A first hello" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
      
  test-unit:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: cat my_workspace/echo-output
      
  test-integration:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: |
          # this will fail intentionally, we'll use SSH to debug and fix
          if [[ $(cat my_workspace/echo-output) == "A first hello" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi   

  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: |
          echo "Deploying!!!"
          cat my_workspace_echo-output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-unit:
          # run only if/when build succeeds
          requires:
            - build
      - test-integration:
          # run only if/when build succeeds
          requires:
            - build
      - deploy:
          requires:
            - test-unit
            - test-integration
